version: "3.9"

services:
  whoami:
    image: traefik/whoami:v1.6.1
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.backend: whoami
        traefik.http.routers.whoami.entrypoints: https
        traefik.http.routers.whoami.tls: "true"
        traefik.http.routers.whoami.tls.certresolver: letsencrypt
        traefik.http.routers.whoami.rule: Host(`who.am.i.${SUBDOMAIN}.${DOMAIN}`)
        traefik.http.services.whoami.loadbalancer.server.port: 80
      placement:
        constraints:
          - "node.labels.cluster==swarm"
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
