version: "3.9"

services:
  loki:
    image: grafana/loki:k59-757eeac
    volumes:
      - ./config.yml:/etc/loki/config.yml:ro
      - ./data:/tmp/loki
    command:
      - "-config.file=/etc/loki/config.yml"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    deploy:
      labels:
        traefik.enable: "false"
      placement:
        constraints:
          - "node.labels.cluster==swarm"
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
