version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.39
    # https://www.jaegertracing.io/docs/1.6/getting-started/
    volumes:
      - ./data:/badger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.backend: jaeger
        traefik.http.routers.jaeger.entrypoints: https
        traefik.http.routers.jaeger.tls: "true"
        traefik.http.routers.jaeger.tls.certresolver: letsencrypt
        traefik.http.routers.jaeger.rule: Host(`jaeger.${SUBDOMAIN}.${DOMAIN}`)
        traefik.http.services.jaeger.loadbalancer.server.port: 16686
      placement:
        constraints:
          - "node.labels.cluster==swarm"
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
