apiVersion: 1

datasources:

- name: Graphite
  type: graphite
  url: http://graphite:8080
  isDefault: true
  access: proxy
  editable: false
  uid: graphite

- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  editable: true
  uid: loki
