{
 "title": "graphite-carbon agents stats",
 "description": "show internal stats agents graphite carbon",
 "tags": [ "internal" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.cache.bulk_queries, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.cache.overflow, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.cache.queries, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.cache.queues, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.cache.size, 'current'))"
    }
   ]
  },
  {
   "title": "statistics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.activeConnections, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.errors, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.blacklistMatches, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.creates, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.whitelistRejects, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.droppedCreates, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.droppedCreates, 'current'))"
    }
   ]
  },
  {
   "title": "average update time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.avgUpdateTime, 'current'))"
    }
   ]
  },
  {
   "title": "updates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.committedPoints, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.metricsReceived, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.pointsPerUpdate, 'current'))"
    },
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.updateOperations, 'current'))"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.cpuUsage, 'current'))"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aggregate(carbon.agents.*.memUsage, 'current'))"
    }
   ]
  }
 ]
}