{
 "title": "Traefik stats [basic]",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "config reload",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "stats_counts.traefik.config.reload.total"
    }
   ]
  },
  {
   "title": "entrypoint requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "stats_counts.traefik.entrypoint.request.total"
    }
   ]
  },
  {
   "title": "open connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "stats.gauges.traefik.entrypoint.connections.open"
    }
   ]
  },
  {
   "title": "requests duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "stats.timers.traefik.entrypoint.request.duration.mean"
    }
   ]
  }
 ]
}