version: "3.9"

services:
  traefik:
    image: traefik:2.8.1
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    environment:
      - TZ=Europe/Moscow
      - TRAEFIK_LOG_LEVEL
      - TRAEFIK_API=true
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS=:443
      - TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_PERMANENT=true
      - TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME=https
      - TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_TO=https
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_WATCH=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_PROVIDERS_DOCKER_ENDPOINT=unix:///var/run/docker.sock
      - TRAEFIK_PROVIDERS_FILE_FILENAME=/etc/traefik/localhost.yml
      - TRAEFIK_PROVIDERS_FILE_WATCH=true
      - TRAEFIK_PROVIDERS_DOCKER_SWARMMODE=true
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT=true
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE_ENTRYPOINT=http
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_TLSCHALLENGE=true
      - TRAEFIK_ACCESSLOG_FILEPATH=/var/log/access.log
      - TRAEFIK_ACCESSLOG_BUFFERINGSIZE=100
      - TRAEFIK_ACCESSLOG_FORMAT=common
      - TRAEFIK_METRICS_STATSD_ADDRESS=graphite:8125
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./acme.json:/acme.json
      - ./localhost.yml:/etc/traefik/localhost.yml:ro
      - ./ssl:/etc/ssl-local:ro
      - type: bind
        source: /var/log/traefik_access.log
        target: /var/log/access.log
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
        traefik.http.middlewares.redirect-to-https.redirectscheme.permanent: 'true'
        traefik.http.routers.traefik.entrypoints: https
        traefik.http.routers.traefik.rule: Host(`monitor.${SUBDOMAIN}.${DOMAIN}`)
        traefik.http.routers.traefik.tls: 'true'
        traefik.http.routers.traefik.tls.certresolver: letsencrypt
        traefik.http.routers.traefik.service: api@internal
        traefik.http.services.traefik-traefik.loadbalancer.server.port: 888
        traefik.http.middlewares.traefik-auth.basicauth.users: ${TRAEFIK_USER_AUTH_BASIC}
        traefik.http.routers.traefik.middlewares: traefik-auth
      placement:
        constraints:
          - "node.labels.cluster==swarm"
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
